spring:
  application:
    name: transfer-fee-calculator

  cloud:
    stream:
      bindings:
        transfers-with-fee:
          content-type: application/json
          producer:
            required-groups: queue
        transfers:
          content-type: application/xml
          # otherwise we get a auto-delete, non-durable queue, applies only to consumers
          group: queue

# by default only 'health' and 'info' endpoints are included
# http://www.baeldung.com/spring-boot-actuators

management:
  endpoints:
    web:
      exposure:
        include: ['*']