spring:
  cloud:
    stream:
      bindings:
        transfers-with-fee:
          content-type: application/json
          producer:
            required-groups: queue
        transfers:
          content-type: application/xml
          # otherwise we get a auto-delete, non-durable queue, applies only to consumers
          group: queue